# GitHub Action Metadata File
# This file defines the action's interface, inputs, outputs, and execution environment
# Reference: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions

# Action identification and description
name: "Upload to Vercel Blob"
description: "Upload files to Vercel Blob storage from GitHub Actions workflows"
author: "dartilesm"

# Input parameters that users can provide when using this action
inputs:
  # Source file or folder path - the file or folder to be uploaded
  source:
    description: "The source path for the blob file or folder"
    required: true

  # Destination path in Vercel Blob storage
  destination:
    description: "The destination path for the blob in Vercel Blob storage (for folders, this will be the base path)"
    required: true

  # Vercel Blob read-write token for authentication
  read-write-token:
    description: "Vercel Blob read-write token (BLOB_READ_WRITE_TOKEN)"
    required: true

# Output values that this action provides to subsequent workflow steps
outputs:
  # URL of the uploaded blob file
  url:
    description: "The URL of the uploaded blob"

# Execution environment configuration
runs:
  using: "node20" # Use Node.js 20 runtime
  main: "dist/index.js" # Entry point script

# Visual branding for GitHub Marketplace
branding:
  icon: "upload-cloud" # Feather icon name
  color: "blue" # Theme color
