name: "Upload to Vercel Blob"
description: "Upload files to Vercel Blob storage from GitHub Actions workflows"
author: "dartilesm"
inputs:
  source:
    description: "The source path for the blob file"
    required: true
  destination:
    description: "The destination path for the blob in Vercel Blob storage"
    required: true
  read-write-token:
    description: "Vercel Blob read-write token (BLOB_READ_WRITE_TOKEN)"
    required: true
outputs:
  url:
    description: "The URL of the uploaded blob"
runs:
  using: "node20"
  main: "src/index.js"
branding:
  icon: "cloud-upload"
  color: "blue"
